name: First WorkFlow 
on: [push]
jobs:
  run-echo-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "SATISH"
      - run: |
          ls
          echo "${{ github.workspace }}"
  example-job:
    name: Save output
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      - run: |
          ls